version: '3.8'

services:
  mongo:
    image: mongo:5
    ports:
      - '27017:27017'

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  frontend:
    build: ./client
    ports:
      - '3000:3000'
